In [1]:
from pathlib import Path

print(Path.cwd())

C:\Users\luisi\Desktop\Bioinformatica\Data Science\Data science II\clinical_trial_pipeline Pre entrega 5\clinical-trial-etl\notebooks

In [8]:
from src.extract import extract_data

In [13]:
df = extract_data(str(csv_path))

print("Dimensiones del dataset:", df.shape)
display(df.head())

Dataset cargado: 1000 filas y 11 columnas
Dimensiones del dataset: (1000, 11)

,Subject_ID,Site_ID,Age,Gender,Enrollment_Date,Treatment_Group,Adverse_Events,Dropout,Systolic_BP,Diastolic_BP,Cholesterol_Level
0,1,49,54,Male,1/1/22,Drug A,0,0,117,74,229
1,2,37,44,Male,1/2/22,Placebo,1,0,111,57,173
2,3,1,58,Male,1/3/22,Drug A,0,1,122,89,220
3,4,25,48,Male,1/4/22,Drug B,0,0,122,85,175
4,5,10,57,Female,1/5/22,Drug A,2,0,105,90,185

In [14]:
print("Dimensiones del dataset:", df.shape)

print("\nTipos de datos:")
print(df.dtypes)

print("\nUso de memoria:")
print(f"{df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

print("\nValores nulos por columna:")
print(df.isnull().sum())

Dimensiones del dataset: (1000, 11)

Tipos de datos:
Subject_ID           int64
Site_ID              int64
Age                  int64
Gender                 str
Enrollment_Date        str
Treatment_Group        str
Adverse_Events       int64
Dropout              int64
Systolic_BP          int64
Diastolic_BP         int64
Cholesterol_Level    int64
dtype: object

Uso de memoria:
0.10 MB

Valores nulos por columna:
Subject_ID           0
Site_ID              0
Age                  0
Gender               0
Enrollment_Date      0
Treatment_Group      0
Adverse_Events       0
Dropout              0
Systolic_BP          0
Diastolic_BP         0
Cholesterol_Level    0
dtype: int64

In [21]:
import importlib
import src.transform

importlib.reload(src.transform)

from src.transform import transform_data

In [22]:
df_clean = transform_data(df)

Nombres de columnas normalizados.
Fecha de inscripción convertida correctamente.
Duplicados eliminados: 0
Filas eliminadas por datos esenciales faltantes: 0
Transformación completada.
Filas finales: 1000
Columnas finales: 11
Valores nulos restantes: 0

In [23]:
print("Tipo de dato:", df_clean["enrollment_date"].dtype)
print("Fechas nulas:", df_clean["enrollment_date"].isna().sum())

display(df_clean[["Enrollment_Date"]] .head() if "Enrollment_Date" in df_clean.columns else df_clean[["enrollment_date"]].head(10))

Tipo de dato: datetime64[us]
Fechas nulas: 0

  enrollment_date
0      2022-01-01
1      2022-01-02
2      2022-01-03
3      2022-01-04
4      2022-01-05
5      2022-01-06
6      2022-01-07
7      2022-01-08
8      2022-01-09
9      2022-01-10

In [24]:
from src.load import load_data

In [25]:
output_path = str(
    project_path / "data" / "processed" / "clinical_trial_clean.parquet"
)

load_data(df_clean, output_path)

Datos guardados correctamente en: C:\Users\luisi\Desktop\Bioinformatica\Data Science\Data science II\clinical_trial_pipeline Pre entrega 5\clinical-trial-etl\data\processed\clinical_trial_clean.parquet
Registros exportados: 1000

In [26]:
from pathlib import Path
import pandas as pd

parquet_path = Path(output_path)

print("¿Existe el archivo?", parquet_path.exists())

df_parquet = pd.read_parquet(parquet_path)

print("Dimensiones originales:", df.shape)
print("Dimensiones transformadas:", df_clean.shape)
print("Dimensiones de Parquet:", df_parquet.shape)

print("\nTipos de datos guardados:")
print(df_parquet.dtypes)

display(df_parquet.head())

¿Existe el archivo? True
Dimensiones originales: (1000, 11)
Dimensiones transformadas: (1000, 11)
Dimensiones de Parquet: (1000, 11)

Tipos de datos guardados:
subject_id                    int64
site_id                       int64
age                           int64
gender                     category
enrollment_date      datetime64[us]
treatment_group            category
adverse_events                int64
dropout                       int64
systolic_bp                   int64
diastolic_bp                  int64
cholesterol_level             int64
dtype: object

,subject_id,site_id,age,gender,enrollment_date,treatment_group,adverse_events,dropout,systolic_bp,diastolic_bp,cholesterol_level
0,1,49,54,Male,2022-01-01,Drug A,0,0,117,74,229
1,2,37,44,Male,2022-01-02,Placebo,1,0,111,57,173
2,3,1,58,Male,2022-01-03,Drug A,0,1,122,89,220
3,4,25,48,Male,2022-01-04,Drug B,0,0,122,85,175
4,5,10,57,Female,2022-01-05,Drug A,2,0,105,90,185

In [27]:
import subprocess
import sys

resultado = subprocess.run(
    [sys.executable, str(project_path / "main.py")],
    capture_output=True,
    text=True
)

print(resultado.stdout)

if resultado.returncode != 0:
    print("ERROR AL EJECUTAR EL PIPELINE:")
    print(resultado.stderr)

=== INICIO DEL PIPELINE ===

ETAPA 1: EXTRACCIÓN
Dataset cargado: 1000 filas y 11 columnas
Registros extraídos: 1000

ETAPA 2: TRANSFORMACIÓN
Nombres de columnas normalizados.
Fecha de inscripción convertida correctamente.
Duplicados eliminados: 0
Filas eliminadas por datos esenciales faltantes: 0
Transformación completada.
Filas finales: 1000
Columnas finales: 11
Valores nulos restantes: 0

ETAPA 3: CARGA
Datos guardados correctamente en: C:\Users\luisi\Desktop\Bioinformatica\Data Science\Data science II\clinical_trial_pipeline Pre entrega 5\clinical-trial-etl\data\processed\clinical_trial_clean.parquet
Registros exportados: 1000

=== PIPELINE FINALIZADO ===